version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build $SolutionName
workflows:
  version: 2
  buildAll:
    jobs:
      - build
      # none
