name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool restore
    - name: Build
      run: dotnet build --no-restore
    - name: Lint
      run: ./scripts/lint.sh
    - name: Test
      run: dotnet test --no-build --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml --verbosity normal
    - name: Generate coverage report
      run: dotnet reportgenerator "-reports:**/TestResults/coverage.cobertura.xml" "-targetdir:coverage-report" "-reporttypes:Html;Badges;TextSummary"
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./coverage-report

  deploy:
    needs: build
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
