name: Publish - Nuget

on:
  workflow_run:
    workflows: ["Build"]
    branches: [develop]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          dotnet restore
          dotnet tool restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Publish to NuGet
        run: nuget push SharpChatwork/bin/Release/SharpChatwork.0.1.0-alpha.snupkg
