name: Publish - Nuget

on:
  workflow_run:
    workflows: ["Build"]
    branches: [develop]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: |
          dotnet restore
          dotnet tool restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Publish to NuGet
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/Egliss/index.json --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
          dotnet nuget push SharpChatwork/bin/Release/SharpChatwork.0.2.4-alpha.nupkg --api-key ${{secrets.EGLISS_TOKEN}} --source "github"
